apiVersion: v1
kind: Secret
metadata:
  namespace: muchtodo
  name: mongodb-secret
  labels:
    app: mongodb
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: cm9vdA==    # root
  MONGO_INITDB_ROOT_PASSWORD: ZXhhbXBsZQ==  # example
