apiVersion: v1
kind: ConfigMap
metadata:
  namespace: muchtodo
  name: backend-config
  labels:
    app: backend
data:
  PORT: "8080"
  LOG_LEVEL: "DEBUG"
  LOG_FORMAT: "json"
  JWT_EXPIRATION_HOURS: "72"
  DB_NAME: "much_todo_db"