apiVersion: v1
kind: Secret
metadata:
  namespace: muchtodo
  name: backend-secret
  labels:
    app: backend
type: Opaque
stringData:
  .env: |
    PORT=8080
    LOG_LEVEL=DEBUG
    LOG_FORMAT=json
    JWT_EXPIRATION_HOURS=72
    DB_NAME=much_todo_db
    MONGO_URI=mongodb://root:example@mongodb:27017/
    JWT_SECRET_KEY=0d50ZsFhdwq93BdakyDn137udKAgnlIdzY3t40BxHni